//------------------------------------------------------------------------
// Copyright(c) 2023 Newkon.
//------------------------------------------------------------------------

#pragma once

#include "pluginterfaces/base/fplatform.h"

// Plain project version file generated by cmake
#include "projectversion.h"

#define stringOriginalFilename "Hardware Synth.vst3"
#if SMTG_PLATFORM_64
#define stringFileDescription "Hardware Synth VST3 (64Bit)"
#else
#define stringFileDescription "Hardware Synth VST3"
#endif
#define stringCompanyName "Newkon\0"
#define stringLegalCopyright "Copyright(c) 2023 Newkon."
#define stringLegalTrademarks "VST is a trademark of Steinberg Media Technologies GmbH"
